#!/bin/bash

### BEGIN INIT INFO
# Provides:             consoleserver
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    consoleserver and serial logger
### END INIT INFO

DAEMON="/usr/local/bin/consoleserver"
ARGS="-c /etc/consoleserver/config.ini"
PIDFILE="/var/run/consoleserver.pid"

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        -b --make-pidfile \
        --exec $DAEMON -- $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/carbage-serve {start|stop}"
    exit 1
    ;;
esac

exit 0
