#!/bin/bash

DAEMON="/usr/local/bin/consoleserver"
ARGS="-c /etc/consoleserver/config.ini"
PIDFILE="/var/run/consoleserver.pid"

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        -b --make-pidfile \
        --exec $DAEMON -- $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/carbage-serve {start|stop}"
    exit 1
    ;;
esac

exit 0
